M48
; DRILL file {KiCad 7.0.9} date Tue 26 Dec 2023 11:28:14 PM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-26T23:28:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X13.97Y2.54
X15.24Y50.8
X66.04Y35.56
X66.04Y7.62
T2
X6.08Y43.18
X6.08Y33.02
T0
M30
